### ISSUE TITLE
managedproperties-service does not export exceptions

### ISSUE THREAD

**Issue by buggerole** [TDC-Netdesign/ManagedProperties#5]
The managedproperties-service bundle provides a number of exceptions to use, but it doesn't export them from the bundle.

managedproperties-service should export these in order to allow others to use the exceptions.

**Comment by mnybon** [comment]
I have changed the POM file to export the exception package from managedproperties-service. I have also changed the test consumer to actually use the exceptions.

A workaround until the next release, is to simply not use the exceptions on the configuration interface. This will cause any exception to be thrown as a runtime exception.
This IS a workaround, i realize it is likely not production quality. It will be fixed in the next release.
